-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE HEALTHCARE_PHARMA_DIST;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.FACILITIES (
  FACILITY_ID VARCHAR(20) NOT NULL, FACILITY_NAME VARCHAR(200), CITY VARCHAR(50), REGION VARCHAR(50), FACILITY_TYPE VARCHAR(30), BED_COUNT INT, ACCREDITATION VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PATIENTS (
  PATIENT_ID VARCHAR(20) NOT NULL, FACILITY_ID VARCHAR(20), AGE_GROUP VARCHAR(20), GENDER VARCHAR(10), PROVINCE VARCHAR(50), INSURANCE_TYPE VARCHAR(30), REGISTRATION_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ENCOUNTERS (
  ENCOUNTER_ID VARCHAR(30) NOT NULL, PATIENT_ID VARCHAR(20), FACILITY_ID VARCHAR(20), ENCOUNTER_DATE TIMESTAMP, DEPARTMENT VARCHAR(50), DIAGNOSIS_CODE VARCHAR(20), LOS_DAYS FLOAT, COST FLOAT, OUTCOME VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MEDICATIONS (
  MED_ID VARCHAR(30) NOT NULL, ENCOUNTER_ID VARCHAR(30), DRUG_NAME VARCHAR(200), CATEGORY VARCHAR(50), QUANTITY INT, UNIT_COST FLOAT, PRESCRIBED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
