-- Generated from generator/demo_specs/aws-thailand-healthcare-pharma-dist.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-healthcare-pharma-dist
-- This is the schema that is actually deployed for THAILAND_HEALTHCARE_PHARMA_DIST.

-- Alerts fire on the bottom tail of Delivery On-Time
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_DELIVERY_ON_TIME) AS T
  FROM RAW.DEMAND_HISTORY
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_DELIVERY_ON_TIME <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_DELIVERY_ON_TIME), 2) AS AVG_DELIVERY_ON_TIME,
  ROUND(AVG(f.KPI_STOCK_OUT_RISK), 2) AS AVG_STOCK_OUT_RISK,
  ROUND(AVG(f.KPI_FORECAST_ACCURACY), 2) AS AVG_FORECAST_ACCURACY,
  ROUND(AVG(f.KPI_SAFETY_STOCK_DAYS), 2) AS AVG_SAFETY_STOCK_DAYS,
  ROUND(AVG(f.KPI_COLD_CHAIN_COMPLIANCE), 2) AS AVG_COLD_CHAIN_COMPLIANCE
FROM RAW.DEMAND_HISTORY f
JOIN RAW.DISTRIBUTION_CENTERS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_DELIVERY_ON_TIME), 2) AS AVG_DELIVERY_ON_TIME,
  ROUND(AVG(f.KPI_STOCK_OUT_RISK), 2) AS AVG_STOCK_OUT_RISK,
  ROUND(AVG(f.KPI_FORECAST_ACCURACY), 2) AS AVG_FORECAST_ACCURACY,
  ROUND(AVG(f.KPI_SAFETY_STOCK_DAYS), 2) AS AVG_SAFETY_STOCK_DAYS,
  ROUND(AVG(f.KPI_COLD_CHAIN_COMPLIANCE), 2) AS AVG_COLD_CHAIN_COMPLIANCE
FROM RAW.DEMAND_HISTORY f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_DELIVERY_ON_TIME) AS KPI_DELIVERY_ON_TIME, AVG(KPI_STOCK_OUT_RISK) AS KPI_STOCK_OUT_RISK, AVG(KPI_COLD_CHAIN_COMPLIANCE) AS KPI_COLD_CHAIN_COMPLIANCE, AVG(KPI_FORECAST_ACCURACY) AS KPI_FORECAST_ACCURACY, AVG(KPI_SAFETY_STOCK_DAYS) AS KPI_SAFETY_STOCK_DAYS FROM RAW.DEMAND_HISTORY),
     en AS (SELECT SUM(KPI_DISTRIBUTION_POINTS) AS KPI_DISTRIBUTION_POINTS, SUM(KPI_EXPIRY_RISK_30D) AS KPI_EXPIRY_RISK_30D FROM RAW.DISTRIBUTION_CENTERS)
  SELECT 1 AS SORT_ORDER, 'Delivery On-Time' AS TITLE, KPI_DELIVERY_ON_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DELIVERY_ON_TIME), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Stock-Out Risk' AS TITLE, KPI_STOCK_OUT_RISK AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_STOCK_OUT_RISK)) AS DECIMAL(38,0))) || ' ' || 'SKUs' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Cold Chain Compliance' AS TITLE, KPI_COLD_CHAIN_COMPLIANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_COLD_CHAIN_COMPLIANCE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Distribution Points' AS TITLE, KPI_DISTRIBUTION_POINTS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_DISTRIBUTION_POINTS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Forecast Accuracy' AS TITLE, KPI_FORECAST_ACCURACY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FORECAST_ACCURACY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Safety Stock Days' AS TITLE, KPI_SAFETY_STOCK_DAYS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SAFETY_STOCK_DAYS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Expiry Risk (30d)' AS TITLE, KPI_EXPIRY_RISK_30D AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_EXPIRY_RISK_30D) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
