-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Pharmaceutical Distribution
-- ============================================================================
USE DATABASE PHARMA_DISTRIBUTION;
USE SCHEMA ML;

-- ML.FORECAST: PHARMA_DEMAND_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.PHARMA_DEMAND_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEMAND_TIMESERIES'),
  SERIES_COLNAME => 'SKU_REGION',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.PHARMA_DEMAND_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.PHARMA_DEMAND_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: DEMAND_SPIKE_DETECTOR
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.DEMAND_SPIKE_DETECTOR(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEMAND_TIMESERIES'),
  SERIES_COLNAME => 'SKU_REGION',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.DEMAND_SPIKE_DETECTOR_RESULTS AS
SELECT * FROM TABLE(ML.DEMAND_SPIKE_DETECTOR!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEMAND_TIMESERIES'), SERIES_COLNAME => 'SKU_REGION', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

