-- ============================================================================
-- 99_RESET.SQL — Reset Pharmaceutical Distribution to clean demo state
-- ============================================================================
USE DATABASE PHARMA_DISTRIBUTION;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_ORDERS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_REPLENISHMENT SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.STOCKOUT_RISK REFRESH;
ALTER DYNAMIC TABLE CURATED.DEMAND_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.SERVICE_LEVEL_METRICS REFRESH;
ALTER DYNAMIC TABLE CURATED.REPLENISHMENT_SIGNALS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PHARMA_DISTRIBUTION.RAW.ORDERS → 450000
-- SELECT COUNT(*) FROM PHARMA_DISTRIBUTION.RAW.DEMAND_HISTORY → 1800000
-- SELECT COUNT(*) FROM PHARMA_DISTRIBUTION.CURATED.STOCKOUT_RISK WHERE DAYS_OF_SUPPLY < 7 → ~47

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS RESUME;
ALTER TASK IF EXISTS APP.TASK_GENERATE_REPLENISHMENT RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_ORDERS RESUME;
